#!/usr/bin/env bash
#
# Installs drey and interposes it in front of every language server found on
# this machine, for every LSP client (Claude Code, Codex, editors).
#
# It does four things, all reversible by scripts/uninstall.sh:
#   1. builds and installs the `drey` binary
#   2. finds each real language server and records its absolute path
#   3. writes ~/.config/drey/config.toml
#   4. writes wrapper scripts to ~/.drey/bin and prepends that to PATH
#
# Nothing is overwritten without a timestamped backup.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="$HOME/.drey/bin"
CONFIG="$HOME/.config/drey/config.toml"
STAMP="$(date +%Y%m%d-%H%M%S)"
MARK_BEGIN="# >>> drey >>>"
MARK_END="# <<< drey <<<"

say() { printf '  %s\n' "$*"; }

# name-in-config : binary-to-look-for : root markers (comma separated)
SERVERS=(
  "rust-analyzer:rust-analyzer:Cargo.toml,rust-project.json"
  "gopls:gopls:go.work,go.mod"
  "typescript-language-server:typescript-language-server:pnpm-workspace.yaml,package.json,tsconfig.json"
  "pyright-langserver:pyright-langserver:pyproject.toml,setup.py"
  "ruff:ruff:pyproject.toml,ruff.toml"
  "clangd:clangd:compile_commands.json,CMakeLists.txt"
  "lua-language-server:lua-language-server:.luarc.json"
  "jdtls:jdtls:pom.xml,build.gradle"
  "ruby-lsp:ruby-lsp:Gemfile,.ruby-lsp"
  "intelephense:intelephense:composer.json"
  "kotlin-lsp:kotlin-lsp:build.gradle.kts,settings.gradle.kts"
  "sourcekit-lsp:sourcekit-lsp:Package.swift"
  "zls:zls:build.zig"
  "solargraph:solargraph:Gemfile"
  "omnisharp:OmniSharp:*.sln"
)

echo
echo "drey install"
echo

# --- 1. the binary ---------------------------------------------------------
say "building and installing drey..."
# Install to an explicit root. Version managers and cargo wrappers redirect the
# default install location, and the wrappers below need an absolute path that
# is certain to be correct.
cargo install --path "$REPO" --root "$HOME/.drey" --force --quiet
DREY="$HOME/.drey/bin/drey"
if [ ! -x "$DREY" ]; then
  echo "drey installed, but $DREY is missing" >&2
  exit 1
fi
say "installed: $DREY"
echo

# --- 2 & 3. discover real servers, write config ----------------------------
mkdir -p "$(dirname "$CONFIG")" "$BIN_DIR"
if [ -f "$CONFIG" ]; then
  cp "$CONFIG" "$CONFIG.backup-$STAMP"
  say "backed up existing config to $CONFIG.backup-$STAMP"
fi

{
  echo "# Generated by drey scripts/install.sh on $(date)."
  echo "# Commands are ABSOLUTE paths to the real servers, so the PATH wrappers"
  echo "# in $BIN_DIR can never cause drey to re-enter itself."
  echo
  echo "[daemon]"
  echo "idle_timeout_secs = 1800"
  echo
} > "$CONFIG"

FOUND=()
for entry in "${SERVERS[@]}"; do
  name="${entry%%:*}"; rest="${entry#*:}"
  binary="${rest%%:*}"; markers="${rest#*:}"

  # Resolve past our own wrappers and past asdf shims to the real executable.
  path=""
  while IFS= read -r candidate; do
    case "$candidate" in
      "$BIN_DIR"/*) continue ;;
    esac
    path="$candidate"; break
  done < <(type -a -p "$binary" 2>/dev/null || true)
  [ -n "$path" ] || continue

  if [[ "$path" == *"/.asdf/shims/"* ]] && command -v asdf >/dev/null 2>&1; then
    real="$(asdf which "$binary" 2>/dev/null || true)"
    [ -n "$real" ] && path="$real"
  fi

  marker_toml=$(printf '"%s", ' ${markers//,/ } | sed 's/, $//')
  {
    echo "[server.$name]"
    echo "command = \"$path\""
    [ -n "$marker_toml" ] && echo "root_markers = [$marker_toml]"
    echo
  } >> "$CONFIG"

  FOUND+=("$name")
  say "found $name -> $path"
done

echo
say "wrote $CONFIG"
echo

# --- 4. wrappers -----------------------------------------------------------
for name in "${FOUND[@]}"; do
  cat > "$BIN_DIR/$name" <<EOF
#!/bin/sh
# Installed by drey. Routes this language server through the shared daemon.
# Remove this file (or run drey's scripts/uninstall.sh) to go back to the
# real \`$name\` on PATH.
exec "$DREY" serve "$name" "\$@"
EOF
  chmod +x "$BIN_DIR/$name"
done
say "wrote ${#FOUND[@]} wrapper(s) to $BIN_DIR"

# --- PATH ------------------------------------------------------------------
# The block goes in BOTH zsh startup files, and it has to be in both:
#
#   .zshenv  is read by every zsh, including the non-interactive ones that GUI
#            editors, launchd jobs and scripts use to spawn a language server.
#            .zshrc alone would miss all of those.
#   .zshrc   is read after .zshenv for interactive shells, and version managers
#            (asdf, rbenv, nvm) prepend their own shims there. Without a second
#            prepend afterwards, those shims sit in front of ours again.
#
# Prepending twice is harmless: the duplicate PATH entry resolves identically.
RC_FILES=()
if [ -f "$HOME/.zshenv" ] || [ -f "$HOME/.zshrc" ] || [ -n "${ZSH_VERSION:-}" ]; then
  RC_FILES+=("$HOME/.zshenv" "$HOME/.zshrc")
else
  RC_FILES+=("$HOME/.bashrc")
fi

for RC in "${RC_FILES[@]}"; do
  if grep -qF "$MARK_BEGIN" "$RC" 2>/dev/null; then
    say "PATH entry already present in $RC"
    continue
  fi
  [ -f "$RC" ] && cp "$RC" "$RC.backup-$STAMP"
  {
    echo ""
    echo "$MARK_BEGIN"
    echo "# Shared language servers. Remove this block to disable drey."
    echo "export PATH=\"\$HOME/.drey/bin:\$PATH\""
    echo "$MARK_END"
  } >> "$RC"
  say "added PATH entry to $RC"
done

echo
echo "Done. Open a new shell, or run:"
echo "    export PATH=\"\$HOME/.drey/bin:\$PATH\""
echo
echo "Check it is working:"
echo "    which rust-analyzer      # should be $BIN_DIR/rust-analyzer"
echo "    drey status              # shows shared servers once a client connects"
echo
echo "To revert everything:"
echo "    $REPO/scripts/uninstall.sh"
echo
